// <auto-generated />
using System;
using MWeb1_2.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace MWeb1_2.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20190928211308_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("MWeb1_2.Models.Marker", b =>
                {
                    b.Property<string>("markerID")
                        .ValueGeneratedOnAdd();

                    b.Property<double>("markerLat");

                    b.Property<double>("markerLng");

                    b.Property<string>("photo");

                    b.Property<string>("photoPath");

                    b.Property<int>("userID");

                    b.HasKey("markerID");

                    b.ToTable("Markers");
                });

            modelBuilder.Entity("MWeb1_2.Models.User", b =>
                {
                    b.Property<int>("userID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("created");

                    b.Property<string>("userEmail");

                    b.Property<string>("userName");

                    b.Property<string>("userPassword");

                    b.Property<bool>("userStatus");

                    b.HasKey("userID");

                    b.ToTable("Users");
                });
#pragma warning restore 612, 618
        }
    }
}
