// <auto-generated />
using MWeb1_2.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace MWeb1_2.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20190926061338_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("MWeb1_2.Models.Marker", b =>
                {
                    b.Property<string>("markerID")
                        .ValueGeneratedOnAdd();

                    b.Property<decimal>("markerLat");

                    b.Property<decimal>("markerLng");

                    b.Property<string>("photo");

                    b.Property<string>("photoPath");

                    b.Property<int>("userID");

                    b.HasKey("markerID");

                    b.ToTable("Markers");
                });
#pragma warning restore 612, 618
        }
    }
}
