// <auto-generated />
using System;
using MWeb_test.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace MWeb_test.Migrations
{
    [DbContext(typeof(Mweb_DataTableFirstContext))]
    [Migration("20191018031701_dool")]
    partial class dool
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("MWeb_test.Models.Comments", b =>
                {
                    b.Property<int>("CommentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("commentID")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Comment")
                        .IsRequired()
                        .HasColumnName("comment");

                    b.Property<int>("MarkerId")
                        .HasColumnName("markerID");

                    b.Property<int>("UserId")
                        .HasColumnName("userID");

                    b.HasKey("CommentId")
                        .HasName("PK_Comment");

                    b.HasIndex("MarkerId");

                    b.HasIndex("UserId");

                    b.ToTable("Comments");
                });

            modelBuilder.Entity("MWeb_test.Models.Markers", b =>
                {
                    b.Property<int>("MarkerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("markerID")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<decimal>("MarkerLat")
                        .HasColumnName("markerLat")
                        .HasColumnType("decimal(10, 6)");

                    b.Property<decimal>("MarkerLng")
                        .HasColumnName("markerLng")
                        .HasColumnType("decimal(10, 6)");

                    b.Property<byte[]>("Photo")
                        .IsRequired()
                        .HasColumnName("photo")
                        .HasColumnType("image");

                    b.Property<string>("PhotoPath")
                        .IsRequired()
                        .HasColumnName("photoPath")
                        .HasMaxLength(255)
                        .IsUnicode(false);

                    b.Property<int>("UserId")
                        .HasColumnName("userID");

                    b.HasKey("MarkerId")
                        .HasName("PK_Marker");

                    b.HasIndex("UserId");

                    b.ToTable("Markers");
                });

            modelBuilder.Entity("MWeb_test.Models.UserSettings", b =>
                {
                    b.Property<int>("SettingId")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("settingID")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<decimal>("CenterLat")
                        .HasColumnName("centerLat")
                        .HasColumnType("decimal(10, 6)");

                    b.Property<decimal>("CenterLng")
                        .HasColumnName("centerLng")
                        .HasColumnType("decimal(10, 6)");

                    b.Property<int>("CenterZoom")
                        .HasColumnName("centerZoom");

                    b.Property<bool>("Gps")
                        .HasColumnName("GPS");

                    b.Property<string>("MapType")
                        .IsRequired()
                        .HasColumnName("mapType")
                        .HasMaxLength(10)
                        .IsUnicode(false);

                    b.Property<int>("PinRadius")
                        .HasColumnName("pinRadius");

                    b.Property<int>("UserId")
                        .HasColumnName("userID");

                    b.HasKey("SettingId")
                        .HasName("PK_Setting");

                    b.HasIndex("UserId");

                    b.ToTable("UserSettings");
                });

            modelBuilder.Entity("MWeb_test.Models.Userss", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("userID")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<byte[]>("Created")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnName("created");

                    b.Property<string>("UserEmail")
                        .IsRequired()
                        .HasColumnName("userEmail")
                        .IsUnicode(false);

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnName("userName")
                        .HasMaxLength(18)
                        .IsUnicode(false);

                    b.Property<string>("UserPassword")
                        .IsRequired()
                        .HasColumnName("userPassword")
                        .HasMaxLength(50)
                        .IsUnicode(false);

                    b.Property<string>("UserStatus")
                        .IsRequired()
                        .HasColumnName("userStatus")
                        .HasMaxLength(19)
                        .IsUnicode(false);

                    b.HasKey("UserId")
                        .HasName("PK_Users");

                    b.ToTable("Userss");
                });

            modelBuilder.Entity("MWeb_test.Models.Comments", b =>
                {
                    b.HasOne("MWeb_test.Models.Markers", "Marker")
                        .WithMany("Comments")
                        .HasForeignKey("MarkerId")
                        .HasConstraintName("FK_Comment_Marker");

                    b.HasOne("MWeb_test.Models.Userss", "User")
                        .WithMany("Comments")
                        .HasForeignKey("UserId")
                        .HasConstraintName("FK_Comment_User");
                });

            modelBuilder.Entity("MWeb_test.Models.Markers", b =>
                {
                    b.HasOne("MWeb_test.Models.Userss", "User")
                        .WithMany("Markers")
                        .HasForeignKey("UserId")
                        .HasConstraintName("FK_Marker_User");
                });

            modelBuilder.Entity("MWeb_test.Models.UserSettings", b =>
                {
                    b.HasOne("MWeb_test.Models.Userss", "User")
                        .WithMany("UserSettings")
                        .HasForeignKey("UserId")
                        .HasConstraintName("FK_Settings_Users");
                });
#pragma warning restore 612, 618
        }
    }
}
